Repository short-d/short-ext, pull requests merged in 2020-03, with the labels that each got.

#24 Add ping listener for the website to know the extistence of extension
  .env.dist
  .gitignore
  README.md
  manifest.json
  package.json
  src/background.ts
  yarn.lock
Labels: enhancement

#25 Fix build script
  README.md
  scripts/build
Labels: size/XS

#26 Fix build script
  scripts/build
Labels: size/XS

#27 Add prettier package to format code
  package.json
  scripts/format
  src/background.ts
  yarn.lock
Labels: size/M

#30 Get version number of extension based on git tag dynamically
  .drone.yml
  .env.dist
  .env.production
  .gitignore
  Dockerfile
  README.md
  manifest.json
  package.json
  scripts/build
Labels: enhancement, size/M

#33 Add .dockerignore file
  .dockerignore
Labels: size/S

#35 Add publishing the extension step to drone CI
  .drone.yml
  .gitignore
  Dockerfile
  package.json
Labels: enhancement, size/M

#37 Update readme with instructions to publish release to chrome store
  README.md
Labels: documentation, size/S

#39 Fix APP_BASE_URL for production extension
  .env.production
Labels: size/XS

#41 Fix dev build instruction in README
  README.md
Labels: documentation, size/XS
